---

  - name: "update apt packages."
    become: yes
    apt:
      update_cache: yes

  - name: "upgrade packages"
    become: yes
    apt:
      upgrade: yes

  - name: "remove dependencies that are no longer required"
    become: yes
    apt:
      autoremove: yes

  - name: "install nodejs and npm"
    become: yes
    apt:
      name: npm
      state: latest
      update_cache: yes

  - name: "install n"
    become: yes
    npm:
      name: n
      global: yes
      production: yes

  - name: "Install node version 12.x"
    shell: |
      curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
      sudo apt install -y nodejs
  - name: "Install pm2"
    become: true
    npm:
      name: pm2
      global: yes
      production: yes
      state: present
  
  - name: "wait 300 seconds for target connection to become reachable/usable."
      command: sleep 300s
