---
  - name: Copy backend files
    become: true
    synchronize:
      src: ../../backend/dist
      dest: /home/ubuntu/
      recursive: true

  - name: Start PM2
    shell: |
      cd /home/ubuntu
      ls -la
      cd backend
      sudo npm install -g npm@latest
      sudo npm install -g webpack-dev-server
      sudo npm install
      sudo npm run build
      sudo pm2 start npm --name backend -- start

