---

- name: "Copy backend tar.gz file and unzipping it"
  unarchive:
    src: ~/project/backend.tar.gz
    dest: /home/ubuntu

- name: Start PM2
  shell: |
    echo "i am here"
    cd /home/ubuntu/
    tar xzvf backend.tar.gz
    ls -la
    npm install
    npm run build
    pm2 start npm --name backend -- start
