---
  - name: Copy backend files
    become: true
    copy:
      src: ~/backend
      dest: /home/ubuntu/

  - name: Start PM2
    shell: |
      cd /home/ubuntu
      ls -la
      cd backend
      sudo npm install -g npm@latest
      sudo npm install -g webpack-dev-server
      sudo npm install
      sudo npm run build
      sudo pm2 start npm --name backend -- start

